language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false
r_build_args: '--no-manual'

r_github_packages:
  - ropenscilabs/datastorr
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
